title: Dans la jungle
remote_theme: oisiflorus/maquillage-danslajungle

defaults:
  -
    scope:
      path: ""
    values:
      layout: location

collections:
  montreal:
  a-propos-de-nous:
    output: true

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings
